import time
from selenium import webdriver # импортируем webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.implicitly_wait(10)
driver.execute_script("window.scrollBy(0, 600);")
s_ruby = driver.find_element_by_id("text-22-sub_row_1-0-2-0-0")
s_ruby.click()
reviews = driver.find_element_by_class_name("reviews_tab")
reviews.click()
star_5 = driver.find_element_by_class_name("star-5")
star_5.click()
comment = driver.find_element_by_id('comment')
comment.send_keys("Nice book!")
name = driver.find_element_by_id('author')
name.send_keys("Bomge")
email = driver.find_element_by_id('email')
email.send_keys("Bomge@google.com")
submit = driver.find_element_by_id("submit")
submit.click()